version: '3.1'

services:
  anthropic-claude-db:
    container_name: anthropic-claude-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: anthropic_claude_user
      POSTGRES_PASSWORD: strongUserPassword
      POSTGRES_DB: anthropic_claude
    volumes:
      - ./db-volume:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"